---
- name: Fedora post install 
  hosts: localhost
  connection: local
  roles:
    - role: "roles/update-fedora"
    - role: "roles/debloat-fedora"
    - role: "roles/rpm-fusion"
    - role: "roles/multimedia-codecs"
    - role: "roles/firewall"
#    - role: "roles/kicksecure"
    - role: "roles/kvm"
    - role: "roles/apps"
    - role: "roles/nvidia"